[package]
name = "rust_hf_decoder"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_hf_decoder"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }

# та же версия, что и в Python (0.22.0)
tokenizers = "0.22.0"

